### PR TITLE
commit.c: Add -F / --file option

### LINKED ISSUE #43: Add support for -F / --file option on commit command
Read the commit message from file via `-F <file>` / `--file=<file>` to better support multi-line commit messages.

### PR DESCRIPTION
**Pull request by charabaruk**
`message` does double duty for the commit message file name as well as the commit message itself, in order to reduce impact on the stack with all the other added variables. To protect against reading past the end of the file, I had to remove the `const` from `message` in order to explicitly provide a null byte at the end of the read.

Closes #43.

### CODE REVIEW

**Comment by sba1** [comment]
Great! Thanks for your contribution. I would however prefer, for the ease of following the code, not to assign different meanings to the variables (i.e., message being a file or a text). To fix it, one could do it as follows:
 1. Create two variables, e.g. message_file_name and message_file_contents and populate them.
 2. Assign message_file_contents to message if needed
 3. Free message_file_contents if needed.

This should simplify further refactoring.

**Comment by charabaruk** [comment]
I can split out the filename from `message` no problem, I only doubled it up originally because of concerns about stack availability on AmigaOS. I'd like to continue using `message` to store the contents of the message file, though, since it remains the commit message regardless of whether it is read from the command line or from a file.

When my main computer stops disk checking and lets me work on it again, I'll update the PR.

**Comment by sba1** [comment]
Am 2020-04-14 13:34, schrieb Chris Charabaruk:
> I can split out the filename from message no problem, I only doubled
> it up originally because of concerns about stack availability on
> AmigaOS. I'd like to continue using message to store the contents of
> the message file, though, since it remains the commit message
> regardless of whether it is read from the command line or from a file.

I'd like to refactor this function some when, especially, when by usimg 
genopts templates. It is better to keep things separate especially for 
this purpose.

**Comment by charabaruk** [comment]
Alright, I've updated the code per your request. Since `message` is no longer serving double duty, I've had to move the check for its assignment to after the message file processing since we know it'll be `NULL` where it was originally located in the code.

**Comment by charabaruk** [comment]
Hey @sba1 seeing as the PR has been updated, could we get this re-reviewed and hopefully merged and released? Thanks.

**Comment by sba1** [comment]
Could you please squash the commits? I would do myself but I lack the time.

**Comment by charabaruk** [comment]
@sba1 done.

**Review by sba1 — APPROVED** [review]
Thanks!

**Pull request merged**
